openapi: 3.0.1
info:
  title: Contracten
  description: Contracten API
  contact:
    name: Test
  version: v0.1
servers:
- url: https://contracten-api-master-test.azurewebsites.net/
security:
 - ApiKey: []
paths:
  /api/personen/{bsn}/contracten:
    get:
      tags:
      - Contracten
      parameters:
      - name: bsn
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          nullable: true
      - name: version
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contract'
components:
  schemas:
    Contract:
      type: object
      properties:
        identificatie:
          type: string
          nullable: true
          description: Unieke sleutel binnen de bron
        bsn:
          type: string
          nullable: true,
          description: Unieke sleutel van een persoon
        titel:
          type: string
          nullable: true,
          description: De titel van het contract
        status:
          type: string
          nullable: true,
          description: De status van het contract
        beginDatum:
          type: string
          format: date-time
          nullable: true,
          description: De datum waarop het contract in gaat
        eindDatum:
          type: string
          format: date-time
          nullable: true,
          description: De datum waarop het contract afloopt
        organisatie:
          type: string
          nullable: true,
          description: De organisatie met wie deze persoon het contract heeft afgesproken
  securitySchemes:
    ApiKey:
     type: apiKey
     description: Please enter the ApiKey
     name: Authorization
     in: header